### ISSUE TITLE
Include relevant license in repo

### ISSUE THREAD

**Issue by mike182uk** [gitevents/gitevents-tito#10]
The `package.json` lists the license as `ISC`. This is the default license that npm uses when generating the `package.json`. This should be reviewed to make sure this is the correct license, and the license documentation should be included as part of the repo (file called `LICENSE`).

**Comment by iancrowther** [comment]
@PatrickHeneise which licence are we using?

**Comment by PatrickHeneise** [comment]
No preference, GPLv3, Apache or MIT are all fine with me.

**Comment by iancrowther** [comment]
https://github.com/gitevents/gitevents-tito/commit/651bc473a81d406a19cab30c1c6d25f328db21ee

**Comment by mike182uk** [comment]
@iancrowther The license contains placeholders https://github.com/gitevents/gitevents-tito/blob/master/LICENCE#L3

**Comment by iancrowther** [comment]
Oh no.. Hmm

**Comment by mike182uk** [comment]
Resolved in 65911b8
