### ISSUE TITLE
Consider extacting getEventDetails into own lib

### ISSUE THREAD

**Issue by mike182uk** [gitevents/gitevents-tito#9]
The method `getEventDetails` deals with extracting the event details from the github payload body. This operation would need to be done by any plugin that wanted to integrate with gitevents. Would it make sense to extract this method out to its own lib which could be required in as a dependency? Sort of like a base plugin which provides common utility methods.

**Comment by PatrickHeneise** [comment]
quick check: for each plugin you don't get the github payload, but the pre-formatted event/talk from https://github.com/gitevents/core/blob/master/gitevents.js#L69, correct?

**Comment by mike182uk** [comment]
Ah excellent, this is already done in core. For some reason this plugin is parsing the raw Github payload. This plugin should be changed to use the pre-formatted event object thats passed in. I'll close this issue and raise a new one for this change.

**Comment by PatrickHeneise** [comment]
:+1:
